#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit on command errors and treat unset variables as an error
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e .fonctions ]; then
	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
	sudo cp ../settings/scripts/.fonctions ./.fonctions
	sudo chmod a+rx .fonctions
fi
source .fonctions
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
dbname=$(ynh_app_setting_get $app dbname)
dbuser=$(ynh_app_setting_get $app dbuser)
dbpass=$(ynh_app_setting_get $app dbpass)


#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP OF THE MAIN DIR OF THE APP
#=================================================

CHECK_SIZE "$final_path"
ynh_backup_abstract "$final_path" "sources"

#=================================================
# BACKUP OF THE NGINX CONFIGURATION
#=================================================

ynh_backup_abstract "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"

#=================================================
# BACKUP OF THE SQL BDD
#=================================================

sudo mongodump --host localhost --port 3017 --username $dbuser --password $dbpass --db $dbname --out dump.sql
CHECK_SIZE "dump.sql"
ynh_backup_abstract "dump.sql" "db.sql"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP SYSTEMD
#=================================================

ynh_backup_abstract "/etc/systemd/system/$app.service" "systemd"
